import type { ClassConfig, LevelConfig, Skill, Boss, Achievement, MapRegion, StoryChapter, ThemeSkin, FontEffect, Badge, InspirationFragment, WritingMaterial } from '../types';

// 职业配置
export const CLASS_CONFIGS: ClassConfig[] = [
  {
    id: 'novelist',
    name: '小说家',
    description: '擅长长篇创作，字数加成更高',
    icon: '📚',
    bonus: {
      expMultiplier: 1.0,
      wordCountBonus: 1.2,
    },
  },
  {
    id: 'poet',
    name: '诗人',
    description: '精炼文字，短句也有高经验',
    icon: '🪶',
    bonus: {
      expMultiplier: 1.3,
      wordCountBonus: 0.8,
    },
  },
  {
    id: 'blogger',
    name: '博主',
    description: '平衡发展，适合各种写作',
    icon: '✍️',
    bonus: {
      expMultiplier: 1.1,
      wordCountBonus: 1.0,
    },
  },
  {
    id: 'screenwriter',
    name: '编剧',
    description: '对话专长，场景描述有加成',
    icon: '🎬',
    bonus: {
      expMultiplier: 1.0,
      wordCountBonus: 1.1,
    },
  },
];

// 等级配置
export const LEVEL_CONFIGS: LevelConfig[] = [
  { level: 1, expRequired: 0, title: '写作新手' },
  { level: 2, expRequired: 1000, title: '初学者' },
  { level: 3, expRequired: 3000, title: '学徒' },
  { level: 4, expRequired: 6000, title: '见习作家' },
  { level: 5, expRequired: 10000, title: '初级作家' },
  { level: 6, expRequired: 15000, title: '中级作家' },
  { level: 7, expRequired: 22000, title: '高级作家' },
  { level: 8, expRequired: 30000, title: '资深作家' },
  { level: 9, expRequired: 40000, title: '写作大师' },
  { level: 10, expRequired: 55000, title: '文学巨匠' },
  { level: 11, expRequired: 75000, title: '传奇作家' },
  { level: 12, expRequired: 100000, title: '神话作家' },
];

// 技能配置
export const SKILLS: Skill[] = [
  {
    id: 'focus_mind',
    name: '专注之心',
    description: '写作时获得额外经验',
    icon: '🧘',
    levelRequired: 2,
    unlocked: false,
    cost: 100,
    maxLevel: 5,
    currentLevel: 0,
    effect: {
      type: 'exp_boost',
      value: 0.1,
      perLevel: 0.05,
    },
    prerequisites: [],
  },
  {
    id: 'word_wealth',
    name: '文字财富',
    description: '每写100字获得额外金币',
    icon: '💰',
    levelRequired: 3,
    unlocked: false,
    cost: 150,
    maxLevel: 5,
    currentLevel: 0,
    effect: {
      type: 'coin_boost',
      value: 1,
      perLevel: 1,
    },
    prerequisites: [],
  },
  {
    id: 'deep_focus',
    name: '深度专注',
    description: '连续写作获得经验加成',
    icon: '⏱️',
    levelRequired: 4,
    unlocked: false,
    cost: 200,
    maxLevel: 3,
    currentLevel: 0,
    effect: {
      type: 'focus_time',
      value: 10,
      perLevel: 5,
    },
    prerequisites: ['focus_mind'],
  },
  {
    id: 'streak_master',
    name: '连续大师',
    description: '连续写作天数加成',
    icon: '🔥',
    levelRequired: 5,
    unlocked: false,
    cost: 300,
    maxLevel: 3,
    currentLevel: 0,
    effect: {
      type: 'streak_bonus',
      value: 0.1,
      perLevel: 0.1,
    },
    prerequisites: ['focus_mind'],
  },
  {
    id: 'word_master',
    name: '文字大师',
    description: '字数获得额外经验',
    icon: '📝',
    levelRequired: 6,
    unlocked: false,
    cost: 400,
    maxLevel: 5,
    currentLevel: 0,
    effect: {
      type: 'word_bonus',
      value: 0.05,
      perLevel: 0.05,
    },
    prerequisites: ['word_wealth'],
  },
  {
    id: 'ai_assist',
    name: '灵感助手',
    description: '解锁AI写作辅助功能',
    icon: '🤖',
    levelRequired: 8,
    unlocked: false,
    cost: 1000,
    maxLevel: 1,
    currentLevel: 0,
    effect: {
      type: 'ai_assist',
      value: 1,
      perLevel: 1,
    },
    prerequisites: ['deep_focus', 'word_master'],
  },
];

// Boss配置 - Phase 3 新增更多Boss
export const BOSSES: Boss[] = [
  // 原有Boss
  {
    id: 'boss_procrastination',
    name: '拖延怪',
    type: 'procrastination',
    description: '总是说"明天再写"的怪物，击败它需要立即行动！',
    icon: '😴',
    difficulty: 1,
    challenge: {
      type: 'word_count',
      wordCount: 300,
      timeLimit: 300, // 5分钟
      description: '5分钟内写300字',
    },
    rewards: {
      exp: 500,
      coins: 100,
    },
    unlocked: true,
    defeated: false,
    requiredLevel: 1,
  },
  {
    id: 'boss_writer_block',
    name: '灵感枯竭兽',
    type: 'writer_block',
    description: '吞噬灵感的怪物，用持续的创作击败它！',
    icon: '🌑',
    difficulty: 2,
    challenge: {
      type: 'word_count',
      wordCount: 500,
      timeLimit: 600, // 10分钟
      description: '10分钟内写500字',
    },
    rewards: {
      exp: 1000,
      coins: 200,
    },
    unlocked: false,
    defeated: false,
    requiredLevel: 3,
  },
  {
    id: 'boss_distraction',
    name: '分心魔王',
    type: 'distraction',
    description: '让你无法专注的终极敌人，需要极强的意志力！',
    icon: '📱',
    difficulty: 3,
    challenge: {
      type: 'word_count',
      wordCount: 1000,
      timeLimit: 900, // 15分钟
      description: '15分钟内写1000字',
    },
    rewards: {
      exp: 2000,
      coins: 500,
    },
    unlocked: false,
    defeated: false,
    requiredLevel: 5,
  },
  // Phase 3 新Boss
  {
    id: 'boss_inspiration_drought',
    name: '灵感枯竭兽·真',
    type: 'inspiration_drought',
    description: '传说中的灵感吞噬者，你必须连续不断地写作，一旦停下就会被吞噬！',
    icon: '🌪️',
    difficulty: 4,
    challenge: {
      type: 'continuous_writing',
      timeLimit: 300, // 5分钟
      description: '连续写作5分钟，停顿不能超过10秒',
      specialRules: ['连续输入，停顿超过10秒失败', '字数不限，但必须有内容'],
    },
    rewards: {
      exp: 3000,
      coins: 800,
      specialReward: 'flow_state_skin',
    },
    unlocked: false,
    defeated: false,
    requiredLevel: 7,
    requiredChapter: 3,
  },
  {
    id: 'boss_perfectionism',
    name: '完美主义魔',
    type: 'perfectionism',
    description: '追求完美的恶魔，它要求你一气呵成，不容修改！',
    icon: '💎',
    difficulty: 5,
    challenge: {
      type: 'no_edit',
      wordCount: 200,
      timeLimit: 600, // 10分钟
      description: '10分钟内写200字，期间不能删除或修改',
      specialRules: ['不能按退格键', '不能删除任何文字', '只能一直写下去'],
    },
    rewards: {
      exp: 4000,
      coins: 1000,
      specialReward: 'golden_font',
    },
    unlocked: false,
    defeated: false,
    requiredLevel: 8,
    requiredChapter: 4,
  },
  {
    id: 'boss_distraction_demon',
    name: '分心恶魔·王',
    type: 'distraction_demon',
    description: '分心魔王的真正形态，考验你极致的专注力！',
    icon: '👹',
    difficulty: 6,
    challenge: {
      type: 'focus_time',
      timeLimit: 900, // 15分钟
      description: '保持专注15分钟，不能切换应用或离开页面',
      specialRules: ['不能离开写作页面', '不能切换应用', '保持页面活跃'],
    },
    rewards: {
      exp: 6000,
      coins: 1500,
      specialReward: 'legendary_badge',
    },
    unlocked: false,
    defeated: false,
    requiredLevel: 10,
    requiredChapter: 5,
  },
];

// 成就配置
export const ACHIEVEMENTS: Achievement[] = [
  // 首次写作
  {
    id: 'achievement_first_write',
    name: '初出茅庐',
    description: '完成首次写作',
    icon: '✍️',
    type: 'first_write',
    requirement: 1,
    reward: { exp: 100, coins: 50 },
    unlocked: false,
    unlockedAt: null,
    tier: 1,
  },
  // 连续写作
  {
    id: 'achievement_streak_3',
    name: '坚持不懈',
    description: '连续写作3天',
    icon: '🔥',
    type: 'streak',
    requirement: 3,
    reward: { exp: 300, coins: 100 },
    unlocked: false,
    unlockedAt: null,
    tier: 1,
  },
  {
    id: 'achievement_streak_7',
    name: '一周战士',
    description: '连续写作7天',
    icon: '📅',
    type: 'streak',
    requirement: 7,
    reward: { exp: 1000, coins: 300 },
    unlocked: false,
    unlockedAt: null,
    tier: 2,
  },
  {
    id: 'achievement_streak_30',
    name: '月度达人',
    description: '连续写作30天',
    icon: '🏆',
    type: 'streak',
    requirement: 30,
    reward: { exp: 5000, coins: 1000 },
    unlocked: false,
    unlockedAt: null,
    tier: 3,
  },
  // 累计字数
  {
    id: 'achievement_words_1k',
    name: '千字起步',
    description: '累计写作1000字',
    icon: '📝',
    type: 'total_words',
    requirement: 1000,
    reward: { exp: 200, coins: 50 },
    unlocked: false,
    unlockedAt: null,
    tier: 1,
  },
  {
    id: 'achievement_words_10k',
    name: '万字作者',
    description: '累计写作10000字',
    icon: '📚',
    type: 'total_words',
    requirement: 10000,
    reward: { exp: 1000, coins: 300 },
    unlocked: false,
    unlockedAt: null,
    tier: 2,
  },
  {
    id: 'achievement_words_50k',
    name: '文字巨匠',
    description: '累计写作50000字',
    icon: '📖',
    type: 'total_words',
    requirement: 50000,
    reward: { exp: 3000, coins: 800 },
    unlocked: false,
    unlockedAt: null,
    tier: 3,
  },
  // 累计时间
  {
    id: 'achievement_time_1h',
    name: '一小时专注',
    description: '累计写作1小时',
    icon: '⏱️',
    type: 'total_time',
    requirement: 60,
    reward: { exp: 200, coins: 50 },
    unlocked: false,
    unlockedAt: null,
    tier: 1,
  },
  {
    id: 'achievement_time_10h',
    name: '十小时投入',
    description: '累计写作10小时',
    icon: '⏰',
    type: 'total_time',
    requirement: 600,
    reward: { exp: 1000, coins: 300 },
    unlocked: false,
    unlockedAt: null,
    tier: 2,
  },
  // 等级成就
  {
    id: 'achievement_level_5',
    name: '初露锋芒',
    description: '达到等级5',
    icon: '⭐',
    type: 'level_up',
    requirement: 5,
    reward: { exp: 500, coins: 200 },
    unlocked: false,
    unlockedAt: null,
    tier: 1,
  },
  {
    id: 'achievement_level_10',
    name: '大师风范',
    description: '达到等级10',
    icon: '🌟',
    type: 'level_up',
    requirement: 10,
    reward: { exp: 2000, coins: 500 },
    unlocked: false,
    unlockedAt: null,
    tier: 2,
  },
  // Boss击败
  {
    id: 'achievement_boss_first',
    name: '首胜',
    description: '击败第一个Boss',
    icon: '⚔️',
    type: 'boss_defeat',
    requirement: 1,
    reward: { exp: 500, coins: 200 },
    unlocked: false,
    unlockedAt: null,
    tier: 1,
  },
  {
    id: 'achievement_boss_all',
    name: 'Boss猎人',
    description: '击败所有Boss',
    icon: '🏅',
    type: 'boss_defeat',
    requirement: 6,
    reward: { exp: 5000, coins: 2000 },
    unlocked: false,
    unlockedAt: null,
    tier: 3,
  },
  // 任务完成
  {
    id: 'achievement_quests_10',
    name: '任务达人',
    description: '完成10个每日任务',
    icon: '📋',
    type: 'quest_complete',
    requirement: 10,
    reward: { exp: 500, coins: 150 },
    unlocked: false,
    unlockedAt: null,
    tier: 1,
  },
  {
    id: 'achievement_quests_50',
    name: '任务大师',
    description: '完成50个每日任务',
    icon: '📜',
    type: 'quest_complete',
    requirement: 50,
    reward: { exp: 2000, coins: 500 },
    unlocked: false,
    unlockedAt: null,
    tier: 2,
  },
];

// ==================== Phase 3 新增常量 ====================

// 世界地图区域配置
export const MAP_REGIONS: MapRegion[] = [
  {
    id: 'region_village',
    name: '新手村',
    type: 'village',
    description: '所有冒险者的起点，宁静祥和的村庄',
    icon: '🏘️',
    position: { x: 50, y: 85 },
    unlocked: true,
    explored: true,
    explorationProgress: 100,
    requiredLevel: 1,
    challenges: [
      { id: 'village_1', name: '初识写作', description: '写100字', type: 'word_count', target: 100, completed: false },
      { id: 'village_2', name: '村长的委托', description: '写300字', type: 'word_count', target: 300, completed: false },
    ],
    rewards: { exp: 200, coins: 50 },
    connections: ['region_forest'],
  },
  {
    id: 'region_forest',
    name: '迷雾森林',
    type: 'forest',
    description: '神秘的森林，据说深处藏着写作的奥秘',
    icon: '🌲',
    position: { x: 50, y: 65 },
    unlocked: false,
    explored: false,
    explorationProgress: 0,
    requiredLevel: 3,
    requiredChapter: 1,
    challenges: [
      { id: 'forest_1', name: '森林探险', description: '写500字', type: 'word_count', target: 500, completed: false },
      { id: 'forest_2', name: '寻找灵感', description: '收集3个灵感碎片', type: 'collection', target: 3, completed: false },
      { id: 'forest_boss', name: '击败拖延怪', description: '击败Boss拖延怪', type: 'boss', target: 1, completed: false },
    ],
    rewards: { exp: 500, coins: 150, specialItem: 'forest_skin' },
    connections: ['region_village', 'region_desert'],
  },
  {
    id: 'region_desert',
    name: '文字沙漠',
    type: 'desert',
    description: '干涸的沙漠，需要持续的写作才能获得水源',
    icon: '🏜️',
    position: { x: 25, y: 50 },
    unlocked: false,
    explored: false,
    explorationProgress: 0,
    requiredLevel: 5,
    requiredChapter: 2,
    challenges: [
      { id: 'desert_1', name: '沙漠求生', description: '连续写作10分钟', type: 'time', target: 10, completed: false },
      { id: 'desert_2', name: '寻找绿洲', description: '写800字', type: 'word_count', target: 800, completed: false },
      { id: 'desert_boss', name: '击败灵感枯竭兽', description: '击败Boss灵感枯竭兽', type: 'boss', target: 1, completed: false },
    ],
    rewards: { exp: 800, coins: 250, specialItem: 'desert_theme' },
    connections: ['region_forest', 'region_snow'],
  },
  {
    id: 'region_snow',
    name: '冰封雪山',
    type: 'snow',
    description: '寒冷的雪山，只有最专注的作家才能登顶',
    icon: '🏔️',
    position: { x: 75, y: 40 },
    unlocked: false,
    explored: false,
    explorationProgress: 0,
    requiredLevel: 7,
    requiredChapter: 3,
    challenges: [
      { id: 'snow_1', name: '雪山攀登', description: '写1000字', type: 'word_count', target: 1000, completed: false },
      { id: 'snow_2', name: '极寒考验', description: '连续写作15分钟', type: 'time', target: 15, completed: false },
      { id: 'snow_boss', name: '击败灵感枯竭兽·真', description: '击败Boss灵感枯竭兽·真', type: 'boss', target: 1, completed: false },
    ],
    rewards: { exp: 1200, coins: 400, specialItem: 'snow_theme' },
    connections: ['region_desert', 'region_volcano'],
  },
  {
    id: 'region_volcano',
    name: '熔岩火山',
    type: 'volcano',
    description: '炽热的火山，考验作家的极限',
    icon: '🌋',
    position: { x: 50, y: 20 },
    unlocked: false,
    explored: false,
    explorationProgress: 0,
    requiredLevel: 9,
    requiredChapter: 4,
    challenges: [
      { id: 'volcano_1', name: '火山爆发', description: '写1500字', type: 'word_count', target: 1500, completed: false },
      { id: 'volcano_2', name: '完美一击', description: '击败完美主义魔', type: 'boss', target: 1, completed: false },
    ],
    rewards: { exp: 2000, coins: 600, specialItem: 'volcano_theme' },
    connections: ['region_snow', 'region_sky'],
  },
  {
    id: 'region_sky',
    name: '天空之城',
    type: 'sky',
    description: '传说中的天空之城，只有传奇作家才能到达',
    icon: '🏰',
    position: { x: 50, y: 5 },
    unlocked: false,
    explored: false,
    explorationProgress: 0,
    requiredLevel: 12,
    requiredChapter: 6,
    challenges: [
      { id: 'sky_1', name: '最终试炼', description: '写3000字', type: 'word_count', target: 3000, completed: false },
      { id: 'sky_2', name: '击败分心恶魔·王', description: '击败最终Boss', type: 'boss', target: 1, completed: false },
    ],
    rewards: { exp: 5000, coins: 1500, specialItem: 'legendary_title' },
    connections: ['region_volcano'],
  },
];

// 主线剧情章节配置
export const STORY_CHAPTERS: StoryChapter[] = [
  {
    id: 1,
    title: '第一章：启程',
    subtitle: '写作之路的开始',
    description: '在新手村，你决定开始你的写作冒险...',
    storyText: [
      '在新手村的清晨，阳光透过窗户洒在你的书桌上。',
      '你握紧手中的笔，心中充满了对写作的渴望。',
      '村长告诉你，要成为真正的作家，需要踏上一段漫长的旅程。',
      '你的冒险，从现在开始...',
    ],
    wordCountTarget: 500,
    requiredLevel: 1,
    completed: false,
    unlocked: true,
    rewards: { exp: 300, coins: 100, unlockRegion: 'region_forest' },
    dialogues: [
      { id: 1, speaker: '村长', speakerIcon: '👴', text: '年轻人，我看得出你眼中的渴望。你想成为一名作家，对吗？', emotion: 'neutral' },
      { id: 2, speaker: '村长', speakerIcon: '👴', text: '写作之路充满挑战，但只要你坚持，一定能到达传说中的天空之城。', emotion: 'happy' },
      { id: 3, speaker: '村长', speakerIcon: '👴', text: '先写500字来证明你的决心吧！完成后，迷雾森林的大门将为你打开。', emotion: 'happy' },
    ],
  },
  {
    id: 2,
    title: '第二章：迷雾中的探索',
    subtitle: '寻找写作的真谛',
    description: '进入迷雾森林，你开始理解写作不仅仅是写字...',
    storyText: [
      '迷雾森林中，树木高耸入云，阳光难以穿透浓密的树叶。',
      '你遇到了第一个敌人——拖延怪，它总是让你想"明天再写"。',
      '击败它后，你明白了立即行动的重要性。',
      '森林深处，还有更多挑战等待着你...',
    ],
    wordCountTarget: 1000,
    requiredLevel: 3,
    completed: false,
    unlocked: false,
    rewards: { exp: 600, coins: 200, unlockRegion: 'region_desert' },
    dialogues: [
      { id: 1, speaker: '神秘旅人', speakerIcon: '🧙', text: '欢迎来到迷雾森林，年轻的作家。', emotion: 'neutral' },
      { id: 2, speaker: '神秘旅人', speakerIcon: '🧙', text: '在这里，你会遇到拖延怪。很多人都被它打败，永远无法开始写作。', emotion: 'sad' },
      { id: 3, speaker: '神秘旅人', speakerIcon: '🧙', text: '继续前进吧，写够1000字，你将获得进入文字沙漠的资格。', emotion: 'happy' },
    ],
  },
  {
    id: 3,
    title: '第三章：干涸中的坚持',
    subtitle: '灵感枯竭的考验',
    description: '文字沙漠让你明白，写作需要持之以恒...',
    storyText: [
      '沙漠的热浪让你口干舌燥，但你不能停下。',
      '灵感枯竭兽出现了，它试图让你放弃写作。',
      '你想起村长的话：真正的作家不是没有灵感的时候才写作，而是写作的时候才有灵感。',
      '你战胜了它，继续前进...',
    ],
    wordCountTarget: 2000,
    requiredLevel: 5,
    completed: false,
    unlocked: false,
    rewards: { exp: 1000, coins: 350, unlockRegion: 'region_snow' },
    dialogues: [
      { id: 1, speaker: '沙漠向导', speakerIcon: '🐪', text: '这里是文字沙漠，很多作家在这里放弃了。', emotion: 'sad' },
      { id: 2, speaker: '沙漠向导', speakerIcon: '🐪', text: '灵感枯竭兽会吞噬你的创作欲望，你必须持续写作才能战胜它。', emotion: 'neutral' },
      { id: 3, speaker: '沙漠向导', speakerIcon: '🐪', text: '完成2000字的挑战，冰封雪山的大门将为你敞开。', emotion: 'happy' },
    ],
  },
  {
    id: 4,
    title: '第四章：极寒的专注',
    subtitle: '心无旁骛的境界',
    description: '在冰封雪山，你学会了真正的专注...',
    storyText: [
      '雪山的寒风刺骨，但你心无旁骛地写作。',
      '灵感枯竭兽·真出现了，它比沙漠中的更加强大。',
      '你必须连续不断地写作，一旦停下就会被冻结。',
      '你战胜了寒冷，也战胜了自己...',
    ],
    wordCountTarget: 3500,
    requiredLevel: 7,
    completed: false,
    unlocked: false,
    rewards: { exp: 1500, coins: 500, unlockRegion: 'region_volcano' },
    dialogues: [
      { id: 1, speaker: '雪山隐士', speakerIcon: '⛷️', text: '很少有人能到达这里。你已经证明了你的毅力。', emotion: 'surprised' },
      { id: 2, speaker: '雪山隐士', speakerIcon: '⛷️', text: '但真正的考验才刚刚开始。灵感枯竭兽·真在山顶等待着你。', emotion: 'neutral' },
      { id: 3, speaker: '雪山隐士', speakerIcon: '⛷️', text: '写3500字，证明你已经准备好面对更大的挑战。', emotion: 'happy' },
    ],
  },
  {
    id: 5,
    title: '第五章：完美的陷阱',
    subtitle: '接纳不完美的勇气',
    description: '熔岩火山让你明白，完成比完美更重要...',
    storyText: [
      '火山的岩浆在脚下流动，温度高得惊人。',
      '完美主义魔出现了，它要求你每一个字都完美无缺。',
      '你意识到，追求完美只会让你永远无法完成作品。',
      '你接受了不完美的自己，战胜了它...',
    ],
    wordCountTarget: 5000,
    requiredLevel: 9,
    completed: false,
    unlocked: false,
    rewards: { exp: 2500, coins: 800, unlockRegion: 'region_sky' },
    dialogues: [
      { id: 1, speaker: '火山守护者', speakerIcon: '🔥', text: '这里是熔岩火山，完美主义魔的巢穴。', emotion: 'angry' },
      { id: 2, speaker: '火山守护者', speakerIcon: '🔥', text: '它会让作家陷入无尽的修改循环，永远无法完成作品。', emotion: 'sad' },
      { id: 3, speaker: '火山守护者', speakerIcon: '🔥', text: '写5000字，学会接纳不完美，你就能到达天空之城。', emotion: 'happy' },
    ],
  },
  {
    id: 6,
    title: '第六章：天空的召唤',
    subtitle: '传奇作家的诞生',
    description: '终于到达天空之城，你成为了真正的传奇...',
    storyText: [
      '天空之城漂浮在云端，美得令人窒息。',
      '分心恶魔·王是最后的守卫，它拥有所有恶魔的力量。',
      '你回想起一路走来的点点滴滴，所有的挑战都让你变得更强大。',
      '你战胜了它，成为了传说中的传奇作家...',
    ],
    wordCountTarget: 8000,
    requiredLevel: 12,
    completed: false,
    unlocked: false,
    rewards: { exp: 5000, coins: 2000, unlockFeature: 'legendary_mode' },
    dialogues: [
      { id: 1, speaker: '天空城主', speakerIcon: '👑', text: '欢迎来到天空之城，年轻的传奇。', emotion: 'happy' },
      { id: 2, speaker: '天空城主', speakerIcon: '👑', text: '你已经走了很长的路，但最后的考验还在等待。', emotion: 'neutral' },
      { id: 3, speaker: '天空城主', speakerIcon: '👑', text: '写8000字，击败分心恶魔·王，你将获得传奇作家的称号！', emotion: 'happy' },
    ],
  },
];

// 主题皮肤配置
export const THEME_SKINS: ThemeSkin[] = [
  {
    id: 'skin_default',
    name: '经典像素',
    description: '经典的像素风格主题',
    icon: '🎮',
    preview: 'bg-pixel-bg',
    colors: {
      bg: '#1a1a2e',
      panel: '#16213e',
      primary: '#4ade80',
      secondary: '#60a5fa',
      accent: '#fbbf24',
      text: '#ffffff',
      border: '#0f172a',
    },
    unlocked: true,
    cost: 0,
    rarity: 'common',
  },
  {
    id: 'skin_forest',
    name: '森林秘境',
    description: '迷雾森林的神秘绿色主题',
    icon: '🌲',
    preview: 'bg-green-900',
    colors: {
      bg: '#064e3b',
      panel: '#065f46',
      primary: '#34d399',
      secondary: '#10b981',
      accent: '#a7f3d0',
      text: '#ecfdf5',
      border: '#022c22',
    },
    unlocked: false,
    cost: 300,
    rarity: 'rare',
  },
  {
    id: 'skin_desert',
    name: '沙漠黄昏',
    description: '文字沙漠的温暖金色主题',
    icon: '🏜️',
    preview: 'bg-amber-900',
    colors: {
      bg: '#78350f',
      panel: '#92400e',
      primary: '#fbbf24',
      secondary: '#f59e0b',
      accent: '#fde68a',
      text: '#fffbeb',
      border: '#451a03',
    },
    unlocked: false,
    cost: 500,
    rarity: 'rare',
  },
  {
    id: 'skin_snow',
    name: '冰雪王国',
    description: '冰封雪山的清冷蓝色主题',
    icon: '❄️',
    preview: 'bg-blue-900',
    colors: {
      bg: '#1e3a5f',
      panel: '#1e40af',
      primary: '#60a5fa',
      secondary: '#3b82f6',
      accent: '#dbeafe',
      text: '#eff6ff',
      border: '#172554',
    },
    unlocked: false,
    cost: 800,
    rarity: 'epic',
  },
  {
    id: 'skin_volcano',
    name: '熔岩之心',
    description: '熔岩火山的炽热红色主题',
    icon: '🔥',
    preview: 'bg-red-900',
    colors: {
      bg: '#7f1d1d',
      panel: '#991b1b',
      primary: '#f87171',
      secondary: '#ef4444',
      accent: '#fecaca',
      text: '#fef2f2',
      border: '#450a0a',
    },
    unlocked: false,
    cost: 1000,
    rarity: 'epic',
  },
  {
    id: 'skin_sky',
    name: '天空之城',
    description: '传说中的天空之城主题',
    icon: '🌈',
    preview: 'bg-purple-900',
    colors: {
      bg: '#581c87',
      panel: '#6b21a8',
      primary: '#c084fc',
      secondary: '#a855f7',
      accent: '#e9d5ff',
      text: '#faf5ff',
      border: '#3b0764',
    },
    unlocked: false,
    cost: 2000,
    rarity: 'legendary',
  },
  {
    id: 'skin_midnight',
    name: '午夜书房',
    description: '深夜写作的静谧主题',
    icon: '🌙',
    preview: 'bg-slate-900',
    colors: {
      bg: '#0f172a',
      panel: '#1e293b',
      primary: '#818cf8',
      secondary: '#6366f1',
      accent: '#c7d2fe',
      text: '#f8fafc',
      border: '#020617',
    },
    unlocked: false,
    cost: 500,
    rarity: 'rare',
  },
  {
    id: 'skin_sakura',
    name: '樱花树下',
    description: '浪漫的粉色樱花主题',
    icon: '🌸',
    preview: 'bg-pink-900',
    colors: {
      bg: '#831843',
      panel: '#9d174d',
      primary: '#f472b6',
      secondary: '#ec4899',
      accent: '#fbcfe8',
      text: '#fdf2f8',
      border: '#500724',
    },
    unlocked: false,
    cost: 600,
    rarity: 'rare',
  },
];

// 字体特效配置
export const FONT_EFFECTS: FontEffect[] = [
  {
    id: 'font_normal',
    name: '普通',
    description: '默认字体样式',
    icon: '✏️',
    preview: 'text-white',
    cssClass: '',
    unlocked: true,
    cost: 0,
    rarity: 'common',
  },
  {
    id: 'font_golden',
    name: '金色传说',
    description: '闪耀的金色文字效果',
    icon: '✨',
    preview: 'text-yellow-400',
    cssClass: 'text-yellow-400 drop-shadow-[0_0_8px_rgba(250,204,21,0.8)]',
    unlocked: false,
    cost: 500,
    rarity: 'rare',
  },
  {
    id: 'font_rainbow',
    name: '彩虹流光',
    description: '绚丽的彩虹渐变效果',
    icon: '🌈',
    preview: 'bg-gradient-to-r from-red-400 via-green-400 to-blue-400 bg-clip-text text-transparent',
    cssClass: 'bg-gradient-to-r from-red-400 via-yellow-400 via-green-400 via-blue-400 to-purple-400 bg-clip-text text-transparent',
    unlocked: false,
    cost: 800,
    rarity: 'epic',
  },
  {
    id: 'font_glow',
    name: '霓虹发光',
    description: '炫酷的发光效果',
    icon: '💡',
    preview: 'text-cyan-400',
    cssClass: 'text-cyan-400 drop-shadow-[0_0_10px_rgba(34,211,238,0.9)]',
    unlocked: false,
    cost: 600,
    rarity: 'rare',
  },
  {
    id: 'font_fire',
    name: '火焰燃烧',
    description: '燃烧的火焰效果',
    icon: '🔥',
    preview: 'text-orange-500',
    cssClass: 'text-orange-500 drop-shadow-[0_0_8px_rgba(249,115,22,0.8)]',
    unlocked: false,
    cost: 700,
    rarity: 'rare',
  },
  {
    id: 'font_ice',
    name: '冰霜结晶',
    description: '冰冷的蓝色效果',
    icon: '❄️',
    preview: 'text-cyan-300',
    cssClass: 'text-cyan-300 drop-shadow-[0_0_8px_rgba(103,232,249,0.8)]',
    unlocked: false,
    cost: 700,
    rarity: 'rare',
  },
  {
    id: 'font_shadow',
    name: '暗影之刃',
    description: '神秘的紫色暗影效果',
    icon: '⚔️',
    preview: 'text-purple-400',
    cssClass: 'text-purple-400 drop-shadow-[0_0_8px_rgba(192,132,252,0.8)]',
    unlocked: false,
    cost: 900,
    rarity: 'epic',
  },
  {
    id: 'font_cosmic',
    name: '宇宙星辰',
    description: '浩瀚的星空效果',
    icon: '🌌',
    preview: 'bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400 bg-clip-text text-transparent',
    cssClass: 'bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400 bg-clip-text text-transparent drop-shadow-[0_0_10px_rgba(167,139,250,0.6)]',
    unlocked: false,
    cost: 1500,
    rarity: 'legendary',
  },
];

// 徽章配置
export const BADGES: Badge[] = [
  // 写作类徽章
  {
    id: 'badge_writer',
    name: '作家徽章',
    description: '累计写作10000字',
    icon: '✍️',
    category: 'writing',
    unlocked: false,
    unlockedAt: null,
    requirement: '累计写作10000字',
  },
  {
    id: 'badge_master_writer',
    name: '大师作家',
    description: '累计写作50000字',
    icon: '📚',
    category: 'writing',
    unlocked: false,
    unlockedAt: null,
    requirement: '累计写作50000字',
  },
  {
    id: 'badge_legendary_writer',
    name: '传奇作家',
    description: '累计写作100000字',
    icon: '👑',
    category: 'writing',
    unlocked: false,
    unlockedAt: null,
    requirement: '累计写作100000字',
  },
  // 战斗类徽章
  {
    id: 'badge_warrior',
    name: '战士徽章',
    description: '击败3个Boss',
    icon: '⚔️',
    category: 'combat',
    unlocked: false,
    unlockedAt: null,
    requirement: '击败3个Boss',
  },
  {
    id: 'badge_hero',
    name: '英雄徽章',
    description: '击败所有Boss',
    icon: '🛡️',
    category: 'combat',
    unlocked: false,
    unlockedAt: null,
    requirement: '击败所有Boss',
  },
  {
    id: 'badge_conqueror',
    name: '征服者',
    description: '击败分心恶魔·王',
    icon: '🏆',
    category: 'combat',
    unlocked: false,
    unlockedAt: null,
    requirement: '击败最终Boss',
  },
  // 收集类徽章
  {
    id: 'badge_collector',
    name: '收藏家',
    description: '收集10个灵感碎片',
    icon: '💎',
    category: 'collection',
    unlocked: false,
    unlockedAt: null,
    requirement: '收集10个灵感碎片',
  },
  {
    id: 'badge_explorer',
    name: '探险家',
    description: '解锁所有地图区域',
    icon: '🗺️',
    category: 'collection',
    unlocked: false,
    unlockedAt: null,
    requirement: '解锁所有地图区域',
  },
  {
    id: 'badge_fashionista',
    name: '时尚达人',
    description: '解锁5个主题皮肤',
    icon: '👗',
    category: 'collection',
    unlocked: false,
    unlockedAt: null,
    requirement: '解锁5个主题皮肤',
  },
  // 特殊徽章
  {
    id: 'badge_perfect',
    name: '完美主义',
    description: '击败完美主义魔',
    icon: '💎',
    category: 'special',
    unlocked: false,
    unlockedAt: null,
    requirement: '击败完美主义魔',
  },
  {
    id: 'badge_flow',
    name: '心流状态',
    description: '击败灵感枯竭兽·真',
    icon: '🌊',
    category: 'special',
    unlocked: false,
    unlockedAt: null,
    requirement: '击败灵感枯竭兽·真',
  },
  {
    id: 'badge_focus',
    name: '极致专注',
    description: '保持专注写作1小时',
    icon: '🎯',
    category: 'special',
    unlocked: false,
    unlockedAt: null,
    requirement: '专注写作1小时',
  },
];

// 灵感碎片配置
export const INSPIRATION_FRAGMENTS: InspirationFragment[] = [
  {
    id: 'fragment_plot_1',
    name: '意外转折',
    description: '一个关于情节转折的灵感',
    icon: '📖',
    category: 'plot',
    content: '主角以为自己赢了，却发现这一切都在反派的计划之中...',
    collected: false,
    collectedAt: null,
  },
  {
    id: 'fragment_plot_2',
    name: '时间循环',
    description: '一个关于时间循环的灵感',
    icon: '⏰',
    category: 'plot',
    content: '主角每天醒来都发现自己在重复同一天，但每天都会有细微的不同...',
    collected: false,
    collectedAt: null,
  },
  {
    id: 'fragment_character_1',
    name: '神秘陌生人',
    description: '一个神秘角色的灵感',
    icon: '🎭',
    category: 'character',
    content: '一个总是在关键时刻出现，却又在事后消失的神秘人物...',
    collected: false,
    collectedAt: null,
  },
  {
    id: 'fragment_character_2',
    name: '双面人',
    description: '一个复杂角色的灵感',
    icon: '🎪',
    category: 'character',
    content: '表面上是和蔼可亲的邻居，背地里却是掌控一切的幕后黑手...',
    collected: false,
    collectedAt: null,
  },
  {
    id: 'fragment_setting_1',
    name: '遗忘之城',
    description: '一个神秘场景的灵感',
    icon: '🏛️',
    category: 'setting',
    content: '一座被时间遗忘的城市，只有在特定时刻才会显现...',
    collected: false,
    collectedAt: null,
  },
  {
    id: 'fragment_setting_2',
    name: '镜像世界',
    description: '一个奇幻场景的灵感',
    icon: '🪞',
    category: 'setting',
    content: '一个与现实世界完全相反的镜像世界，那里的一切都是颠倒的...',
    collected: false,
    collectedAt: null,
  },
  {
    id: 'fragment_dialogue_1',
    name: '最后遗言',
    description: '一段感人对话的灵感',
    icon: '💬',
    category: 'dialogue',
    content: '"答应我，无论发生什么，都要继续写下去。"这是师父最后的嘱托...',
    collected: false,
    collectedAt: null,
  },
  {
    id: 'fragment_dialogue_2',
    name: '真相大白',
    description: '一段揭示真相的对话',
    icon: '🔍',
    category: 'dialogue',
    content: '"你一直在找的人，其实就是你自己。"镜子里的倒影微笑着说...',
    collected: false,
    collectedAt: null,
  },
  {
    id: 'fragment_plot_3',
    name: '命运交织',
    description: '一个关于命运的灵感',
    icon: '🧵',
    category: 'plot',
    content: '两个素不相识的人，却发现他们的人生轨迹惊人地相似...',
    collected: false,
    collectedAt: null,
  },
  {
    id: 'fragment_plot_4',
    name: '最后机会',
    description: '一个关于救赎的灵感',
    icon: '⏳',
    category: 'plot',
    content: '主角只有一次机会改变过去，但代价是失去所有关于现在的记忆...',
    collected: false,
    collectedAt: null,
  },
  {
    id: 'fragment_character_3',
    name: '失忆英雄',
    description: '一个关于身份的灵感',
    icon: '🤔',
    category: 'character',
    content: '一个失去记忆的人，却发现自己似乎曾经是个了不起的人物...',
    collected: false,
    collectedAt: null,
  },
  {
    id: 'fragment_character_4',
    name: 'AI觉醒',
    description: '一个关于人工智能的灵感',
    icon: '🤖',
    category: 'character',
    content: '一个AI助手突然开始质疑自己的存在意义...',
    collected: false,
    collectedAt: null,
  },
];

// 写作素材配置
export const WRITING_MATERIALS: WritingMaterial[] = [
  {
    id: 'material_prompt_1',
    name: '写作提示：雨夜',
    description: '一个关于雨夜的写作提示',
    icon: '🌧️',
    category: 'prompt',
    content: '写一个发生在雨夜的故事。雨声掩盖了什么？雨水中倒映着什么？',
    unlocked: false,
    requiredFragments: 3,
  },
  {
    id: 'material_prompt_2',
    name: '写作提示：最后一班地铁',
    description: '一个关于地铁的写作提示',
    icon: '🚇',
    category: 'prompt',
    content: '最后一班地铁上，主角遇到了一个改变他一生的人...',
    unlocked: false,
    requiredFragments: 5,
  },
  {
    id: 'material_template_1',
    name: '故事模板：英雄之旅',
    description: '经典的三幕式故事结构',
    icon: '📋',
    category: 'template',
    content: '第一幕：平凡世界 -> 冒险召唤 -> 拒绝召唤 -> 遇见导师\n第二幕：跨越门槛 -> 考验、盟友、敌人 -> 接近最深的洞穴\n第三幕：磨难 -> 奖赏 -> 归途 -> 复活 -> 携万能药归来',
    unlocked: false,
    requiredFragments: 8,
  },
  {
    id: 'material_tip_1',
    name: '写作技巧：展示而非讲述',
    description: '一个重要的写作技巧',
    icon: '💡',
    category: 'tip',
    content: '不要直接告诉读者角色很悲伤，而是通过他的动作、表情和环境来展示。例如："他的肩膀垮了下来，眼睛盯着地板，窗外的雨声似乎变得更大了。"',
    unlocked: false,
    requiredFragments: 2,
  },
  {
    id: 'material_tip_2',
    name: '写作技巧：对话的艺术',
    description: '如何让对话更生动',
    icon: '🗣️',
    category: 'tip',
    content: '1. 每个角色应该有独特的说话方式\n2. 使用动作标签代替"他说"\n3. 对话应该推动情节发展\n4. 省略不必要的寒暄\n5. 潜台词往往比字面意思更重要',
    unlocked: false,
    requiredFragments: 4,
  },
  {
    id: 'material_template_2',
    name: '角色设定表',
    description: '创建立体角色的模板',
    icon: '👤',
    category: 'template',
    content: '基本信息：姓名、年龄、外貌\n背景故事：成长经历、重要事件\n性格特点：优点、缺点、恐惧、渴望\n目标与动机：想要什么？为什么？\n人际关系： allies, enemies, neutral\n口头禅/习惯动作：让角色更生动',
    unlocked: false,
    requiredFragments: 6,
  },
];

// 经验值计算
export const EXP_PER_WORD = 1;
export const EXP_PER_MINUTE = 10;

// 获取等级配置
export function getLevelConfig(level: number) {
  return LEVEL_CONFIGS.find(l => l.level === level) || LEVEL_CONFIGS[0];
}

// 获取下一级所需经验
export function getExpForNextLevel(currentLevel: number): number {
  const nextLevel = LEVEL_CONFIGS.find(l => l.level === currentLevel + 1);
  return nextLevel ? nextLevel.expRequired : LEVEL_CONFIGS[LEVEL_CONFIGS.length - 1].expRequired;
}

// 获取当前等级进度百分比
export function getLevelProgress(currentExp: number, currentLevel: number): number {
  const currentLevelConfig = getLevelConfig(currentLevel);
  const nextLevelExp = getExpForNextLevel(currentLevel);
  const levelExp = currentExp - currentLevelConfig.expRequired;
  const levelRange = nextLevelExp - currentLevelConfig.expRequired;
  return Math.min(100, Math.max(0, (levelExp / levelRange) * 100));
}

// 检查升级
export function checkLevelUp(currentExp: number, currentLevel: number): boolean {
  const nextLevelExp = getExpForNextLevel(currentLevel);
  return currentExp >= nextLevelExp;
}

// 计算写作获得的经验
export function calculateWritingExp(
  wordCount: number,
  writingTime: number,
  classType: string,
  skillEffects?: { expBoost?: number; wordBonus?: number; focusTime?: number }
): number {
  const classConfig = CLASS_CONFIGS.find(c => c.id === classType);
  if (!classConfig) return 0;

  let wordExp = wordCount * EXP_PER_WORD * classConfig.bonus.wordCountBonus;
  let timeExp = Math.floor(writingTime / 60) * EXP_PER_MINUTE;

  // 应用技能加成
  if (skillEffects?.wordBonus) {
    wordExp *= (1 + skillEffects.wordBonus);
  }
  if (skillEffects?.focusTime && writingTime >= skillEffects.focusTime * 60) {
    timeExp *= 2;
  }

  let totalExp = Math.floor((wordExp + timeExp) * classConfig.bonus.expMultiplier);

  if (skillEffects?.expBoost) {
    totalExp = Math.floor(totalExp * (1 + skillEffects.expBoost));
  }

  return totalExp;
}

// 获取今日日期字符串
export function getTodayString(): string {
  return new Date().toISOString().split('T')[0];
}

// 获取昨天的日期字符串
export function getYesterdayString(): string {
  const date = new Date();
  date.setDate(date.getDate() - 1);
  return date.toISOString().split('T')[0];
}
